#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from raxmon_cli.common import run_action
from raxmon_cli.utils import str_to_dict, str_to_list

OPTIONS = [
    [['--entity-id'], {'dest': 'entity_id', 'help': 'Parent Entity ID'}],
    [['--label'], {'dest': 'label', 'help': 'Check label'}],
    [['--type'], {'dest': 'type', 'help': 'Check type'}],
    [['--details-file'], {'dest': 'details_file', 'help': 'Check details [file]'}],
    [['--details-args'], {'dest': 'details_args', 'help': 'Check details [args]'}],
    [['--details-timeout'], {'dest': 'details_timeout', 'help': 'Check details [timeout]'}],
    [['--timeout'], {'dest': 'timeout', 'help': 'Check timeout'}],
    [['--period'], {'dest': 'period', 'help': 'Check period'}],
    [['--monitoring-zones'], {'dest': 'monitoring_zones', 'help': 'A list of monitoring zones'}],
    [['--target-alias'], {'dest': 'target_alias', 'help': 'Target alias'}],
    [['--target-hostname'], {'dest': 'target_hostname', 'help': 'Target hostname'}],
    [['--target-resolver'], {'dest': 'target_resolver', 'help': 'Target resolver'}]
]

REQUIRED_OPTIONS = ['entity_id', 'type']

def callback(driver, options, args, callback):
    details = {}
    options.monitoring_zones = str_to_list(options.monitoring_zones)
    if options.details_file is not None:
        details['file'] = options.details_file
        if options.details_args is not None:
            details['args'] = str_to_list(options.details_args)
        if options.details_timeout is not None:
            details['timeout'] = options.details_timeout

    en = driver.get_entity(entity_id=options.entity_id)
    result = driver.create_check(label=options.label, timeout=options.timeout,
                                 period=options.period, entity=en,
                                 monitoring_zones=options.monitoring_zones,
                                 target_alias=options.target_alias,
                                 target_hostname=options.target_hostname,
                                 target_resolver=options.target_resolver,
                                 type=options.type,
                                 details=details,
                                 who=options.who,
                                 why=options.why)

    callback(result)

run_action(OPTIONS, REQUIRED_OPTIONS, 'checks', 'create', callback)
